const TokenType = {
    // Keywords
    KEYWORD: 'KEYWORD',
    
    // Identifiers and literals
    IDENTIFIER: 'IDENTIFIER',
    NUMBER: 'NUMBER',
    STRING: 'STRING',
    TEMPLATE_STRING: 'TEMPLATE_STRING',
    TEMPLATE_EXPRESSION: 'TEMPLATE_EXPRESSION',
    
    // Operators
    OPERATOR: 'OPERATOR',
    ASSIGNMENT: 'ASSIGNMENT',
    OPTIONAL_CHAINING: 'OPTIONAL_CHAINING',
    NULLISH_COALESCING: 'NULLISH_COALESCING',
    UNION: 'UNION',
    INTERSECTION: 'INTERSECTION',
    
    // Punctuation
    SEMICOLON: 'SEMICOLON',
    COMMA: 'COMMA',
    DOT: 'DOT',
    COLON: 'COLON',
    QUESTION_MARK: 'QUESTION_MARK',
    
    // Brackets
    LEFT_PAREN: 'LEFT_PAREN',
    RIGHT_PAREN: 'RIGHT_PAREN',
    LEFT_BRACE: 'LEFT_BRACE',
    RIGHT_BRACE: 'RIGHT_BRACE',
    LEFT_BRACKET: 'LEFT_BRACKET',
    RIGHT_BRACKET: 'RIGHT_BRACKET',
    LEFT_ANGLE: 'LEFT_ANGLE',
    RIGHT_ANGLE: 'RIGHT_ANGLE',
    
    // Special
    EOF: 'EOF',
    ERROR: 'ERROR'
};

module.exports = TokenType; 